version: '3.7'

services:
  pg-backup:
    depends_on:
      - postgres
    container_name: pg-backup
    image: pg-backup
    networks:
      - webnet
    env_file:
      - .env
    volumes:
      - ./backups:/opt/app/backups
  
  postgres:
    container_name: test-db
    image: postgres:12.10-alpine3.15
    environment:
      POSTGRES_PASSWORD: ${TEMP_POSTGRES_PASSWORD}
      POSTGRES_USER: ${TEMP_POSTGRES_USER}
    ports:
      - 5432:5432
    networks:
      - webnet

networks:
  webnet: